 let allTours = [
	 {link: 'https://novipovorot.pp.ua/page-Kharkiv-Christmas.html', linkName: 'Харьков Рождество'},
	 {link: 'https://novipovorot.pp.ua/page-Arabat-baths.html', linkName: 'Арабатские Термы И Розовое Озеро'},
	 {link: 'https://novipovorot.pp.ua/page-Kharkiv-Poltava-Christmas.html', linkName: 'Рождество Харьков И Полтава'},
	 {link: 'https://novipovorot.pp.ua/page-Carpathians-2022.html', linkName: 'Карпаты - 2022'},
	 {link: 'https://novipovorot.pp.ua/page-dnipro-new-year.html', linkName: 'Новогодние Огни Днепра'},
	 {link: 'https://novipovorot.pp.ua/page-murland.html', linkName: 'Мурляндия'},
	 {link: 'https://novipovorot.pp.ua/page-give-a-paw.html', linkName: 'Дай Лапу'},
	 {link: 'https://novipovorot.pp.ua/page-two-zoos.html', linkName: 'Два Зоопарка'},
	 {link: 'https://novipovorot.pp.ua/page-Kiev-Kharkiv-Poltava.html', linkName: 'Киев. Харьков. Полтава'},
	 {link: 'https://novipovorot.pp.ua/page-cheese-farm-tasting.html', linkName: 'Сырная Ферма С Дегустацией'},
	 {link: 'https://novipovorot.pp.ua/page-Scythian-camp-Khortytsya.html', linkName: 'Скифский Стан Хортица'},
	 {link: 'https://novipovorot.pp.ua/page-Kharkov-ball-of-chrysanthemums.html', linkName: 'Харьков. Бал Хризантем'},
	 {link: 'https://novipovorot.pp.ua/page-Villa-Del-Vino.html', linkName: 'VILLA DEL VINO'},
	 {link: 'https://novipovorot.pp.ua/page-Volnogorsk-Maldives.html', linkName: 'Вольногорские Мальдивы'},
	 {link: 'https://novipovorot.pp.ua/page-zhu-zhu-park-Dnipro.html', linkName: 'Жу-Жу Парк'},
	 {link: 'https://novipovorot.pp.ua/page-Mezhyhirya-Uman-pearls-of-love.html', linkName: 'Межигорье. Умань. Перлина Кохання'},
	 {link: 'https://novipovorot.pp.ua/page-Roses-Farm-Waterfall.html', linkName: 'Розы, Ферма, Водопад'},
	 {link: 'https://novipovorot.pp.ua/page-Kharkiv-Chrysanthemums-Disneyland.html', linkName: 'Харьков, Хризантемы, Диснейленд'},
	 {link: 'https://novipovorot.pp.ua/page-cheese-farm.html', linkName: 'Сырная Ферма И Пасека'},
	 {link: 'https://novipovorot.pp.ua/page-Askania-Nova-Safari.html', linkName: 'Аскания Нова Сафари'},
	 {link: 'https://novipovorot.pp.ua/page-Pink-Lake.html', linkName: 'Розовое Oзеро'},
	 {link: 'https://novipovorot.pp.ua/page-Beer.html', linkName: 'Пиво'},
	 {link: 'https://novipovorot.pp.ua/page-Hortica.html', linkName: 'Хортица'},
	 {link: 'https://novipovorot.pp.ua/page-Yacht-club-and-Aquazoo.html', linkName: 'Яхтклуб И AQUAZOO'},
	 {link: 'https://novipovorot.pp.ua/page-Vilkovo-Oysters-Shabo.html', linkName: 'Вилково, Устрицы И Шабо'},
	 {link: 'https://novipovorot.pp.ua/page-zoo.html', linkName: 'Зоопарк-Замок-Oзеро'},
	 {link: 'https://novipovorot.pp.ua/page-Zaporizhzhia-on-Dnieper.html', linkName: 'Запорожье На Днепре'},
	 {link: 'https://novipovorot.pp.ua/page-balloon-festival.html', linkName: 'Фестиваль Воздушных Шаров'},
	 {link: 'https://novipovorot.pp.ua/page-Svyatogorsk-and-Soledar.html', linkName: 'Святогорск И Соледар'},
	 {link: 'https://novipovorot.pp.ua/page-Six-Days-in-the-Carpathians.html', linkName: '6 Дней В Карпатах'},
	 {link: 'https://novipovorot.pp.ua/page-Lviv-for-weekend.html', linkName: 'Львов На Выходные'},
	 {link: 'https://novipovorot.pp.ua/page-wine.html', linkName: 'Вино'},
	 {link: 'https://novipovorot.pp.ua/page-yavorovskaya-niagara.html', linkName: 'Яворовская Ниагара'},
	 {link: 'https://novipovorot.pp.ua/page-Turkey.html', linkName: 'Турция'},
	 {link: 'https://novipovorot.pp.ua/page-Karpati.html', linkName: 'Карпаты'},
	 {link: 'https://novipovorot.pp.ua/page-Kharkov.html', linkName: 'Хлопковые Горы Харькова'},
	 {link: 'https://novipovorot.pp.ua/page-Georgia.html', linkName: 'Грузия'},
	 {link: 'https://novipovorot.pp.ua/page-cofe-Isla.html', linkName: '50 Оттенков Кофе Isla'},
	 {link: 'https://novipovorot.pp.ua/page-Stambul.html', linkName: 'Стамбул - Столица Тюльпанов'},
	 {link: 'https://novipovorot.pp.ua/page-lions-and-horses.html', linkName: 'Львята И Лошадки'},
	 {link: 'https://novipovorot.pp.ua/page-Dzharylgach.html', linkName: 'Джарылгач - Украинские Мальдивы'},
	 {link: 'https://novipovorot.pp.ua/page-TicToc-pati.html', linkName: 'Tik Tok Pati'},
	 {link: 'https://novipovorot.pp.ua/page-gold-mines.html', linkName: 'Золотые Прииски Закарпатья'},
	 {link: 'https://novipovorot.pp.ua/page-eight-march.html', linkName: 'Букет К 8 Марта'},
	 {link: 'https://novipovorot.pp.ua/page-Odessa-on-march.html', linkName: 'Одесса'},
	 {link: 'https://novipovorot.pp.ua/page-LOL.html', linkName: 'ЛОЛ'},
	 {link: 'https://novipovorot.pp.ua/page-Limonariy.html', linkName: 'Лимонарий'}
];
		
 for(var i = 0; i < allTours.length; i++) {
     document.write(
       '<a class="dropdown-item" href="' + allTours[i].link + '">' + allTours[i].linkName + '</a>'
     );
}
